### ISSUE TITLE
Adding label prop at text field

### ISSUE THREAD

**Issue by yyk121** [yogakurniawan/vue-tel-input-vuetify#1]
### Is your feature request related to a problem? Please describe...

Currently the label for the text field is fixed

### Describe the solution you'd like

Add a prop 'label' to the text field so user can define their own label

### Describe alternatives you've considered

None

### Additional context

![image](https://user-images.githubusercontent.com/56155469/76280260-2e6d8000-62cc-11ea-9dd8-7a4d4bb0e978.png)

**Comment by yogakurniawan** [comment]
hi @yyk121 
thank you so much for submitting this issue.
sorry for very long delay in responding your issue.
i have fixed this issue by adding new prop called `text-field-label` so user can define their own label.

you may upgrade this library to latest version which is **v.1.1.2**

again thank you so much for using my library
