### ISSUE TITLE
Add a focus event

### ISSUE THREAD

**Issue by AEQPAC** [yogakurniawan/vue-tel-input-vuetify#17]
### Is your feature request related to a problem? Please describe...

We can't listen if the focus is taken by the textfield, for example, to edit the select field when it happens (CSS, etc...)

### Describe the solution you'd like

Add an event to listen the textfield focus. In fact, like `@blur`, just repeat further the existing Vuetify `@focus` event.

### Describe alternatives you've considered

None that isn't ugly

### Additional context

![Screenshot 2020-07-15 at 12 04 19](https://user-images.githubusercontent.com/60916518/87532563-a4775e80-c693-11ea-98b9-bc39582ab5c5.png)

**Comment by yogakurniawan** [comment]
hi @AEQPAC this issue has been fixed in version **1.2.8.**
let me know if you still get the same issue
