### ISSUE TITLE
Missing margin between flag and country

### ISSUE THREAD

**Issue by dhstack** [yogakurniawan/vue-tel-input-vuetify#18]
## Current behavior

There is no space between the flag and country name in the country drop down. There is correct margin in the box. This may be related to the "scoped" update in `1.2.7`.
![image](https://user-images.githubusercontent.com/2013388/87719504-753f1b00-c781-11ea-9d83-12dbfb84067d.png)

## Expected behavior

There should be a 5px margin between the flag and the country name in the country dropdown.

## Versions
1.2.8

**Libraries:**

- **vue** version: 2.6.11

**Environment:**

- Device: Desktop
- OS: Windows
- Browser: Chrome
- Browser Version: 83

**Comment by yogakurniawan** [comment]
@dhstack thanks for submitting this issue.
it's now fixed in version 1.2.10.
let me know if you still have the same issue.

**Comment by dhstack** [comment]
Looks good, thanks!
