### ISSUE TITLE
The component fails to load as a plugin and the documentation is incorrect

### ISSUE THREAD

**Issue by edwardsph** [yogakurniawan/vue-tel-input-vuetify#2]
## Current behavior

The documentation says:
```js
import Vue from 'vue';
import VueTelInput from 'vue-tel-input-vuetify';
import vuetify from "./plugins/vuetify";

Vue.use(VueTelInputVuetify, {
  vuetify,
});
```
This will obviously fail because VueTelInputVuetify is not defined but when it is corrected the console reports that v-text-field and v-select are not registered as components suggesting the work to set this up as a plugin is incorrect. The embedded example works because it is use the component locally not as a plugin. It would be good if the example matched the installation example.

Note there is also a `console.log(vuetifyFramework);` in `src/index.js` which should be removed.

## Expected behavior

It worked in 1.1.0 when loaded into a page locally as a component.
```js
import { VueTelInputVuetify } from 'vue-tel-input-vuetify'
export default {
  components: {
    VueTelInputVuetify,
  },
}
```  
It would be better if it worked as a plugin as was attempted in the later releases.

## Versions

Version 1.1.0 was OK but 1.1.3 is failing

## Additional context

Add any other context about the bug here.

**Comment by yogakurniawan** [comment]
hi @edwardsph 

thank you so much for using my plugin :)
I will sort out this issue and will update you once fixed.

**Comment by yogakurniawan** [comment]
hi @edwardsph 

i have fixed the issue, you may upgrade to version [1.1.6](https://www.npmjs.com/package/vue-tel-input-vuetify)

installation guide has been updated as well, you might want to follow this new installation guide.

Install the plugin into Vue:

```javascript
  // src/plugins/vuetify.js

  import Vue from 'vue';
  import Vuetify from 'vuetify';
  import 'vuetify/dist/vuetify.min.css'

  Vue.use(Vuetify);

  export default new Vuetify({
  });

```

```javascript
// src/main.js

import Vue from 'vue';
import VueTelInputVuetify from 'vue-tel-input-vuetify';
import vuetify from "./plugins/vuetify";

Vue.use(VueTelInputVuetify, {
  vuetify,
});

new Vue({
  vuetify,
  render: (h) => h(App),
}).$mount("#app");

```

let me know if you have still have any issues. I will work on it ASAP :)

Thank you.

**Comment by edwardsph** [comment]
Thanks for the incredibly fast response - I look forward to testing it again as soon as I can.

**Comment by yogakurniawan** [comment]
@edwardsph absolutely you are very welcome :)

**Comment by dhstack** [comment]
@yogakurniawan I'm having this issue too on `v1.1.6`.

![image](https://user-images.githubusercontent.com/2013388/82620243-f7f29200-9ba5-11ea-8e84-5f89031e1094.png)

I installed it per the latest documentation. Any idea what's going on?

**Comment by yogakurniawan** [comment]
hi @dhstack 

can you try to update the code in this file `src/plugins/vuetify.js` with this code.
let me know if this is working.

 ```
 import Vue from 'vue';
  import Vuetify from 'vuetify';
  import 'vuetify/dist/vuetify.min.css'

  Vue.use(Vuetify);

  export default new Vuetify({
  });
```

**Comment by yogakurniawan** [comment]
hi @dhstack 

i just created a repository to show the basic usage of this library.
you might want to check this. 
Thanks
https://github.com/yogakurniawan/vue-tel-input-vuetify-example

**Comment by dhstack** [comment]
@yogakurniawan Thanks for the quick reply. Updating my `vuetify.ts` file with your code worked. I would like to use the `vuetify-loader` method of that file for tree shaking though (as described in the -[Vuetify docs](https://vuetifyjs.com/en/getting-started/quick-start/)).

Is that possible?

**Comment by Anele-Komana** [comment]
Hi, I am using vuetify-loader, here is my vuetify.js 

`import Vue from "vue"
import Vuetify from "vuetify/lib"
import "vuetify/dist/vuetify.min.css"
// import "../theme/default.styl"

Vue.use(Vuetify, {
  theme: {
    primary: "#000",
    secondary: "#454647",
    accent: "#ef5f32",
    yellow: "#f9b346",
    error: "#FF5252",
    info: "#2196F3",
    success: "#4CAF50",
    warning: "#FFC107"
  },
  options: {
    customProperties: true
  }
})

export default Vuetify
`

and my main.js 

`import VueTelInputVuetify from "vue-tel-input-vuetify"
import Vuetify from "@/plugins/vuetify"

Vue.use(VueTelInputVuetify, {
  Vuetify
})
`

and i get the below error 
![Capture](https://user-images.githubusercontent.com/29726992/83975343-b4ad5880-a8f3-11ea-8da7-7ec228cb2939.PNG)

**Comment by robertofd1995** [comment]
> hi @dhstack
> 
> can you try to update the code in this file `src/plugins/vuetify.js` with this code.
> let me know if this is working.
> 
> ```js
> import Vue from 'vue';
> import Vuetify from 'vuetify';
> import 'vuetify/dist/vuetify.min.css'
> 
> Vue.use(Vuetify);
> 
> export default new Vuetify({
> });
> ```

I don't know why but with the following config I still have the error that @dhstack reported

```
import Vue from 'vue'
import Vuetify from 'vuetify/lib'
import es from 'vuetify/src/locale/es'
import 'vuetify/dist/vuetify.min.css'

Vue.use(Vuetify)

export default new Vuetify({
  theme: {
    options: {
      customProperties: true
    },
    themes: {
      light: {
        primary: '#224177',
        secondary: '#EE9D32',
        accent: '#224177'
        // error: '#FF5252',
        // info: '#2196F3',
        // success: '#4CAF50',
        // warning: '#FFC107'
      }
    }
  },
  lang: {
    locales: { es },
    current: 'es'
  },
  icons: {
    iconfont: 'mdi'
  }
})

```

**Comment by edwardsph** [comment]
> @yogakurniawan Thanks for the quick reply. Updating my `vuetify.ts` file with your code worked. I would like to use the `vuetify-loader` method of that file for tree shaking though (as described in the -[Vuetify docs](https://vuetifyjs.com/en/getting-started/quick-start/)).
> 
> Is that possible?

I got the plugin working with the documented installation mechanism but this means modifying the vuetify plugin for the sake of just this one component. I agree with @dhstack - it would be good to have vuetify-loader support so it works with the vuetify plugin installed like this:
```js
// src/plugins/vuetify.js

import Vue from 'vue';
import Vuetify from 'vuetify/lib';

Vue.use(Vuetify);

export default new Vuetify({
});
```
Currently this throws 2 errors saying v-select and v-test-field are not registered.

**Comment by LizanLycan** [comment]
Same here, i got the theme configuration and it doesn't work. Throw the errors:
`v-select and v-test-field are not registered.`

**Comment by Tofandel** [comment]
We need to find a solution for vuetify loader to work..
https://github.com/vuetifyjs/vuetify-loader/issues/70

**Comment by Tofandel** [comment]
Current solution in plugins vuetify
```js
import Vuetify, { VTextField, VSelect } from 'vuetify/lib';

Vue.use(Vuetify, {
  components: { VTextField, VSelect },
});
```

**Comment by Tofandel** [comment]
Since my PR has been merged, the correct way to import this package with vuetify loader is `import VueTelInputVuetify from "vue-tel-input-vuetify/src/components/vue-tel-input-vuetify"`

**Comment by yogakurniawan** [comment]
thank you so much @Tofandel for your PR and I apologies, I haven't had chance to fix this issue

**Comment by yogakurniawan** [comment]
@Tofandel sorry I made small update to simplify the import the package with vuetify loader.
it is now like this 

`import VueTelInputVuetify from "vue-tel-input-vuetify/lib/vue-tel-input-vuetify.vue"`

in the latest version 1.1.10

**Comment by Tofandel** [comment]
@yogakurniawan If you want it to be even simpler rename it to index.vue, it can be loaded as `vue-tel-input-vuetify/lib`

**Comment by yogakurniawan** [comment]
@Tofandel got it 👍 
i already made it simple now it can be loaded as `vue-tel-input-vuetify/lib`

**Comment by Tofandel** [comment]
Okay, perfect, now you just need to add a note in the readme that you need to add in vue.config.js
```
  transpileDependencies: [
    'vuetify',
    'vue-tel-input-vuetify',
  ],
```
And you can close this issue

**Comment by yogakurniawan** [comment]
@Tofandel okay I have updated to export plugin.js in index.js. README.md is also updated.
can you review it ?

**Comment by Tofandel** [comment]
Perfect :+1:

**Comment by yogakurniawan** [comment]
cool 👍

**Comment by dhstack** [comment]
The new version is now working for me with no errors. Thanks!

**Comment by edwardsph** [comment]
Thanks for persisting with this - great work.

**Comment by Marsh93** [comment]
Hello everyone, I am using the component with vite, however I see some errors of the type:

```
[Vue warn]: Unknown custom element: <v-select>
[Vue warn]: Unknown custom element: <v-text-field>
```

Has anyone used it with Vite? By the way, I have tried some proposed solutions without any success.

```
"vue-tel-input-vuetify": "^1.5.3",
"vuetify": "^2.6.14",
"vue": "2.7",
```

Currently my configuration goes as follows

**main.js**

```
import Vue from "vue";
import { vuetify, VuetifyPlugin } from "./vuetify";
import VueTelInputVuetify from 'vue-tel-input-vuetify';
```

```
Vue.use(VueTelInputVuetify, {
   vuetify,
});
```

**Use in SFC**
```
<vue-tel-input-vuetify
       :filled="!CellPhoneNumber"
       v-model="CellPhoneNumber"
       label="Cell Phone Number"
       :maxLen="maxLen"
       placeholder="Enter Cell Phone Number..."
       :disabledFetchingCountry="true"
       :defaultCountry="defaultCountry"
       :error-messages="errorMessageCell"
       :preferredCountries="preferredCountries"
       @input="CellPhoneError">
</vue-tel-input-vuetify>
```
