### ISSUE TITLE
Dense and outlined styles

### ISSUE THREAD

**Issue by QADRAX** [yogakurniawan/vue-tel-input-vuetify#21]
### Is your feature request related to a problem? Please describe...

I have the need to use this phone component in my vuetify application where all the other inputs have the outlined and dense styles, currently I cannot set these props to this component.

![Capture](https://user-images.githubusercontent.com/8767361/88263039-a65fa400-ccc9-11ea-9ec5-c859862f3dc1.PNG)

### Describe the solution you'd like

The solution would be for outlined and dense props to travel to the v-text-field and v-select component embedded in this telephone-input. The outlined property is currently present in this component but does not travel to the v-select component.

**Comment by tonoarnau** [comment]
I am having the same issue. It would be great to have this solution. Really appreciated.

**Comment by dieyus** [comment]
+1

**Comment by yogakurniawan** [comment]
hi @QADRAX @tonoarnau @dieyus 
thank you all for the valuable inputs
I have the lib to have dense and outlined props for both select and text field.
it's available in version 1.2.11  🎉

**Comment by QADRAX** [comment]
Now works perfect.
THANKS!
