### ISSUE TITLE
When used in a v-form and the form is reset, country is reset too

### ISSUE THREAD

**Issue by deRaaf** [yogakurniawan/vue-tel-input-vuetify#24]
## Current behavior

When v-form is reset with $refs.form.reset() country is reset too, which results in an empty field.

## Expected behavior

Country field shows default country when accessing to form the second time.

**Comment by shunjid** [comment]
@yogakurniawan Any solution regarding this?

**Comment by Tofandel** [comment]
Same issue, reseting the form results in the country field to be empty instead of the default country
