### ISSUE TITLE
Error when applying function "reset" of v-form

### ISSUE THREAD

**Issue by alanscordoba** [yogakurniawan/vue-tel-input-vuetify#25]
Using this component within v-form and applying the reset function throws errors:

Error in getter for watcher "phoneObject.valid": "Error: Invalid phone number, expected a string"
Error: Invalid phone number, expected a string

Apparently the error happens because the "reset" function sets the value of phone.number to null

**Comment by yogakurniawan** [comment]
@alanscordoba thank you for raising this issue. I really appreciate it :clap: 
it is now fixed in version v1.2.13 :tada:

**Comment by alanscordoba** [comment]
I was able to verify that in the new version the problem is solved. Thank you very much.
