### ISSUE TITLE
Countries with the same country code do not both show up as options - only one does

### ISSUE THREAD

**Issue by dhstack** [yogakurniawan/vue-tel-input-vuetify#4]
## Current behavior
The dropdown menu does not let countries with the same code (e.g. Canada and United States, Russia and Kazakhstan) show up at the same time.

## Expected behavior
Both countries with the same code should show up on the list at the same time. Even though they both have the "+1" country code as this may be confusing for users in cases where IP address detection is inaccurate.

## Versions
`v1.2.8`

**Libraries:**

- **vue** version: 2.6.11

**Environment:**

- Device: Desktop
- OS: Windows 10
- Browser: Chrome
- Browser Version: 83

## Additional context

This can be reproduced if in the US or Canada by setting the `defaultCountry` to not one of those (e.g. China: "CN").

**Comment by MaksymMedved** [comment]
The same situation with some countries having the same country code (e.g., Russia and Kazakhstan).

**Comment by miguelcabreja90** [comment]
Some solution for the missing countries given the same code for example Dominican Republic, Puerto Rico?

**Comment by brunosmm** [comment]
The fix is change on the v-select component to use the "iso2" in the item-value.

@yogakurniawan I will send a pull request for this fix.

**Comment by yogakurniawan** [comment]
hi @brunosmm 
thank you for submitting the PR, i will check very soon

**Comment by yogakurniawan** [comment]
hi @brunosmm 
I have merged your PR. it's available on version **v1.2.16**
Can you help check if it has no issues on your side ?
Thank you!

**Comment by brunosmm** [comment]
@yogakurniawan,

Seems all good, the fix worked!

**Comment by dhstack** [comment]
Works for me too! Thanks!

**Comment by miguelcabreja90** [comment]
Works Tks you
