### ISSUE TITLE
Feature Request: Use v-bind="$attrs" and v-on"$listeners"

### ISSUE THREAD

**Issue by kauanschaeffer** [yogakurniawan/vue-tel-input-vuetify#50]
### Is your feature request related to a problem?

Yes, it is. I'd like to pass a menu-props to the v-select, but It doesnt receive it.
So I realised that lots of props from vuetify are declared explicitly, and thought of suggesting to add the v-bind="$attrs" and v-on="$listeners", or even, just add a prop menu-props and set to v-select.

### Describe the solution you'd like

The new prop added or a dinamic approach to this.

### Describe alternatives you've considered

I only thought those two.

### Additional context

I created a wrapper using the vue-tel-input-vuetify, and I'd like the vue-tel-input-vuetify to receive any vuetify prop and propagate, specially the one I mentionted: menu-props.

**Comment by yogakurniawan** [comment]
Hi @kauanschaeffer 
Thank you for your PR, it has been merged and deployed as version [1.3.0](https://www.npmjs.com/package/vue-tel-input-vuetify/v/1.3.0) 🎉
