### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by EmirhanKucuk** [yogakurniawan/vue-tel-input-vuetify#58]
Hello,
there is a console.log() error which caused by an unused variable.
I found that error in node_modules/lib/vue-tel-input-vuetify.vue.
Variable is **textFieldClasses** 

![image](https://user-images.githubusercontent.com/75630517/131650594-768d8971-a62b-4fb6-8c1e-8d2ec490f7d2.png)

**Comment by EBBozkurt** [comment]
Same here !

**Comment by yogakurniawan** [comment]
Hi @EmirhanKucuk @EBBozkurt 

sorry for the issue, I have fixed it in this version **v1.4.1**
can you upgrade the library to **v1.4.1** and let me know if you still found the same issues ?
thank you

**Comment by EmirhanKucuk** [comment]
Hello @yogakurniawan 
thanks for your reply. The issue is fixed.
Have a nice day.
